### ISSUE TITLE
Play: ignores selection and shows all facilities on map

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#100]
select baseball + beacon hill

![play bug](https://dl.dropbox.com/s/m2e35zyaid3pefc/play-facility-bug.png?dl=1)

**Comment by tyrelsouza** [comment]
Okay, I am not seeing this at all.
![My Screenshot](https://www.dropbox.com/s/edghfp0ptub9cv3/This_is_what_we_see.png?dl=1)

**Comment by cspanring** [comment]
Are all changes pushed?

-----Original Message-----

**Comment by tyrelsouza** [comment]
Yes.
