### ISSUE TITLE
Explore: if facilitytype is not found in a park and neighborhood, search returns all parks and facilities for neighborhood

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#102]
I think the problem is somewhere there https://github.com/MAPC/bostonparks/commit/c6972f8fc33b5c32782b03549f5c956f82e27a15#L0R92

**Comment by tyrelsouza** [comment]
Do you have any examples of this happening?

**Comment by tyrelsouza** [comment]
Fixed from 

https://github.com/MAPC/bostonparks/commit/0f1dbbcdf8592169eb71658fe8ad57586db26291
