### ISSUE TITLE
Park Page: list nearby T and Bus stops

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#105]
...since Google doesn't expose transit directions through API

Problems:
- our transit data doesn't contain bus numbers, therefore provides little benefit to users
- data maintenance: if we use internal transit data layer, how do we keep it up-to-date in case of bus line changes, etc.? how often do changes happen and how do we get notified to update?

Solution:
- mbta API if available, to query surrounding stations incl. line numbers

**Comment by cspanring** [comment]
could be solved with GTFS directions integration as mentioned in #106

**Comment by tyrelsouza** [comment]
So how involved do you want this to be? Prompt for a leaving time? Just showing lines?

**Comment by cspanring** [comment]
Let's start with showing lines

**Comment by tyrelsouza** [comment]
Showing a list, or mapping the lines on the map?

**Comment by cspanring** [comment]
Ideally the stations are mapped around the park, showing the lines in an infobubble onclick. Let's start with a list of stations that are within walking distance, 0.5mi ..?

e.g.
- station_name (line1, line2, line3)
- station_name (line1, line2, line3)

**Comment by tyrelsouza** [comment]
The information we have for the MBTA stops, makes the icons line up for the T logos on the MAP, but not the BASEMAP, there is some discrepancy between where the symbols are on both the map and basemap.

**Comment by cspanring** [comment]
That's fine. On rapid transit stops it's always the issue where you put the label-point - center of the station, entrance, platform, etc.? There is never a good solution to it.

Can we make the icons smaller, maybe half of the size?
And center the icons on the point, without any X or Y offset, eliminating the little arrow on the bottom of the icon.

**Comment by tyrelsouza** [comment]
Yeah, I just tossed together an ugly image to at least get something there. and set it to the 32x37 that your other icons are. I'm going to assign this to Marilyn to provide a new icon.

**Comment by tyrelsouza** [comment]
Thank you Marilyn.
