### ISSUE TITLE
park list: center box height is greater than browser window height

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#11]
max-height should be less than browser height, with scrollbars inside box

**Comment by marilynfletcher** [comment]
Christian - Is this for the desktop display only?

**Comment by cspanring** [comment]
I've noticed it on Desktop, but didn't check it on mobile yet.

**Comment by marilynfletcher** [comment]
It's currently not on the mobile or tablet display, but I wondered if we should not add an internal page scrollbar for those devices. We can try it an see how user-friendly it is.

**Comment by cspanring** [comment]
Priority for next week is definitely desktop, we can improve mobile later and I don't want this to block work on other issues.
