### ISSUE TITLE
map icons should be part of facility type model class

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#110]
as opposed to static files. content editors who add a new facility type currently can't update the map icons.

**Comment by tyrelsouza** [comment]
How would you like this done? Have a foreign key to a map icon? Or have them upload their own image for every new facility? I'm leaning towards the former, but either are doable!

**Comment by tyrelsouza** [comment]
Are we going to force the users to upload an image, or will this be a choice? currently I have it returning an image if there is one, and then defaulting to the old style if there isn't one.

**Comment by cspanring** [comment]
Yes, a facility type requires an icon. It should be up to the user to decide to show the default icon (and upload it again). We need to make that clear to content editors how to generate a new map icon.

**Comment by cspanring** [comment]
follow-up issue: #124

**Comment by tyrelsouza** [comment]
alright, I made this required in the code, and finished uploading images on our site.

Christian: 
    are we forcing a standard size for these?

**Comment by cspanring** [comment]
The map icons we refer to usually come in a standard size, 32x37, we could add a help_text with that information. The JavaScript is optimized for icons with those dimensions.

**Comment by tyrelsouza** [comment]
Got it, the help text is in place.
