### ISSUE TITLE
Explore: use parkmap layer as background basemap

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#114]

**Comment by tyrelsouza** [comment]
I think this is done, right? The explore page opens with your special map? Please reopen if wrong.

**Comment by cspanring** [comment]
Just re-opening and applying the "Done" label to keep track of it and verify later, can't do it right now. Is it live on your dev server? Don't see it there.

**Comment by marilynfletcher** [comment]
use the same map as the home page, called parkmap, a basemap rendering with bright green parks.

**Comment by tyrelsouza** [comment]
Okay now this is done on explore.

```
bp.init_map("parkmap");
```
