### ISSUE TITLE
Trip page: add trailmap legend

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#115]
A simple list explaining the line colors on the background map, see http://trailmap.mapc.org => Map Legend.

**Comment by tyrelsouza** [comment]
I'm going to do this the exact same way that trailmap does it, with an overlay that pops up.

**Comment by cspanring** [comment]
Is there no other way to place the legend? I don't think the Trailmap solution is very good, it's better on the mobile version though http://trailmap.mapc.org/m/

**Comment by tyrelsouza** [comment]
I was given no direction except "like trailmap" so if this is what you want, it can be done.

**Comment by tyrelsouza** [comment]
Is that better? Just committed new code to make it like the mobile version.

**Comment by cspanring** [comment]
Well, it doesn't really match the style of other UI elements. I was referring to the trailmap as an example that has a legend element and didn't mean that we should copy it. The legend should show information while maintaining the look&feel of the site. Sorry for not being clear enough.

**Comment by tyrelsouza** [comment]
@marilynfletcher can you style this now? The code for it is in parkmap/templates/parkmap/trip.html in the #legend section.

I took the css from trailmap and put it at the bottom of the main stylesheet.

thanks.
