### ISSUE TITLE
Add public user management (registration, profiles, etc.)

### ISSUE THREAD

**Issue by marilynfletcher** [MAPC/bostonparks#121]
Need to determine what information is collected Registration is required to post a Park Story.

**Comment by cspanring** [comment]
I think we can start with
- (required) username
- (required) email
- (optional) first name
- (optional) last name
- favorite park

...and then think about 
- description, short-bio
- occupation
- age
- gender
- ...

**Comment by cspanring** [comment]
I recently started using http://www.django-userena.org/ for registration and user management purposes.

I think we're also interested in leveraging existing social/oauth logins (like Facebook and Twitter) that users can use to sign-up. But I've never implemented anything like that, just looked at packages like https://github.com/flashingpumpkin/django-socialregistration , which seems to be straightforward to add.

**Comment by marilynfletcher** [comment]
Adding dropdown menu for user management
