### ISSUE TITLE
Add image upload feature

### ISSUE THREAD

**Issue by hastclair** [MAPC/bostonparks#123]

**Comment by tyrelsouza** [comment]
Admin pages only

**Comment by tyrelsouza** [comment]
"thumbnail size"  2x places

**Comment by tyrelsouza** [comment]
Partially done, all I need to do is get it in the InfoWindows.

Example: http://bpa-mobile.appropriatesolutions.com/park/boston-common/

**Comment by tyrelsouza** [comment]
Also available on the admin 
http://bpa-mobile.appropriatesolutions.com/admin/parkmap/park/110/  
http://bpa-mobile.appropriatesolutions.com/admin/parkmap/park/

if you search for Boston-common.

**Comment by cspanring** [comment]
I don't have access to your admin interface.

**Comment by tyrelsouza** [comment]
Christian: I'll email you a username/password, thought we had back end setup for you guys, unless you've pulled, or want me to send screenshots.
