### ISSUE TITLE
Closest X parks to address?

### ISSUE THREAD

**Issue by tyrelsouza** [MAPC/bostonparks#125]
Has this ever been discussed?

**Comment by cspanring** [comment]
Not to my knowledge. Why do you need it?

```
from django.contrib.gis.geos import GEOSGeometry
address_geom = 'POINT(%f %f)' % (address_lon, address_lat)
address_point = GEOSGeometry(address_geom)
nearest_five_parks = Park.objects.distance(address_point).order_by('-distance')[:5]
```

**Comment by tyrelsouza** [comment]
I was just suggesting it as a feature, wasn't sure if it was discussed. Maybe as another feature on the trip page.

**Comment by cspanring** [comment]
I think this feature will become more useful in a mobile application: "Show me all Parks/Playgrounds/etc. within 3 miles".

**Comment by tyrelsouza** [comment]
Oh yeah even better!

**Comment by tyrelsouza** [comment]
Closing because the repo moved and I want this off my open issues on github.
