### ISSUE TITLE
IE issue

### ISSUE THREAD

**Issue by hastclair** [MAPC/bostonparks#129]
Boston Green Map does not work on Internet Explorer. Susan thinks it is it the same problem that S. Florida with some embed code. Can you fix it?

**Comment by cspanring** [comment]
Just looked at it in IE10 on Windows 7, only a few minor visual problems there, nothing major and site is fully functional. 
![screen shot 2013-07-08 at 8 28 14 pm](https://f.cloud.github.com/assets/89122/765527/f19e3684-e82e-11e2-804f-b6e6284794e0.png)
Which version are you referring to? IE8 can't be supported.
Also, the main repository is now at https://github.com/codeforboston/bostongreenmap
