### ISSUE TITLE
Crash fixes- to prevent Safari on ipads from crashing

### ISSUE THREAD

**Issue by hastclair** [MAPC/bostonparks#130]
When using an iPad to view bostongreenmap.org, all site features are functional, however, user experiences crashes under 2 conditons:
1. When using Bing Aerial Images, if user zooms in with pinch gesture before all images have loaded, Safari will crash.
2. When initially loading the page, if user zooms or scrolls before all elements of page have loaded, Safari will crash.

Suggest preventing user input until all assets have loaded.

**Comment by cspanring** [comment]
Hm, not able to reproduce this behavior on an iPad 3 Retina with iOS 6 on WiFi. Are there any more details from the device?

**Comment by cspanring** [comment]
I have another idea that I need to test for rendering the park geometries, which might fix the issue and make the site better compatible with older devices (issue reported on iPad 1, iOS 5 presumably).
