### ISSUE TITLE
improve usability in "Play" section on homepage

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#15]
1. Only activity dropdown is shown by default
2. neighborhood dropdown becomes visible when activity was selected (slides open or so)
3. only neighborhoods that have parks with facilities with selected activity should be shown in the neighborhoods dropdown

**Comment by cspanring** [comment]
fixed with #9

**Comment by marilynfletcher** [comment]
Christian -- 

I'm continuing work on the templates right now (I had to leave early today, and did not finish), so if you're looking at them, please wait a little longer, I'm almost done. 

Marilyn 

----- Original Message -----
