### ISSUE TITLE
add friendsgroup lookup model to park

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#3]

**Comment by marilynfletcher** [comment]
Hi Christian - 

We'll be digging into this this afternoon. 

Marilyn 

----- Original Message -----

From: "Christian Spanring" reply@reply.github.com 
To: "Marilyn Fletcher" mfletcher@appropriatesolutions.com 
Sent: Thursday, April 26, 2012 10:20:37 AM 
Subject: [bostonparks] add friendsgroup lookup model to park (#3) 

---

Reply to this email directly or view it on GitHub: 
https://github.com/MAPC/bostonparks/issues/3

**Comment by tyrelsouza** [comment]
Hey Christian,
    When I look into this issue, I notice we do not have a friendsgroup class in the models. What type of information would go here?

**Comment by cspanring** [comment]
Bare minimum like name and url for now.

**Comment by tyrelsouza** [comment]
Do you have any fake data we could load in, or should we make up our own? I'll create that and push that class out in a few minutes.

**Comment by cspanring** [comment]
There is currently no data compiled. If you need an example record, please add The Emerald Necklace Conservancy http://www.emeraldnecklace.org/ for the Emerald Necklace park.
