### ISSUE TITLE
play: show list of found facilities

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#41]

**Comment by marilynfletcher** [comment]
Do you want this to display as text or icon?

**Comment by cspanring** [comment]
can we do icon with title in 'alt' attribute?

**Comment by marilynfletcher** [comment]
Currently the icon is showing on the map...  do you want the icons listed under the park name in the text box as well?

**Comment by cspanring** [comment]
no, we only need them on the map.
