### ISSUE TITLE
park slugs are not unique

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#5]
e.g. http://bostonparks.mapc.org/park/charles-river-reservation/

**Comment by marilynfletcher** [comment]
This function was originally coded here: https://github.com/MAPC/bostonparks/commit/8a0fbca2d2764a8fa7857333340642ab1306e190#L4R49

The code was removed, so before we put it back and reload the data, is there a problem with it and will it mess up your fixtures and migrations?

**Comment by cspanring** [comment]
as long as there is only 1 save method per model class it should be fine.
