### ISSUE TITLE
Add "ALL" choice to Neighborhood dropdown (Play)

### ISSUE THREAD

**Issue by marilynfletcher** [MAPC/bostonparks#54]

**Comment by marilynfletcher** [comment]
Can you tell me what you want to happen when "All" is selected?

For example, if the Activity "Cricket" is selected, there are 2 towns available.  Is "All" also an option?  If the user selects "All", do we display all the parks in all towns with cricket?  Or do we reset the neighborhood AND the activity list to show all?

**Comment by hastclair** [comment]
I think All should always be an option. So if you click all and choose Cricket you get a list of parks from both towns and a limited zoom dependent on the spatial relation of the parks with Cricket. You can not choose all for activities only neighborhood.

**Comment by cspanring** [comment]
I think technically it's the same thing as selecting no neighborhood: the search just returns facilities without limiting the result to any particular neighborhood.

In terms of UI and implementation, an additional "All" neighborhood option with an empty value would probably to the trick.

**Comment by tyrelsouza** [comment]
Yeah it seems to be a little bit more difficult than that as neighborhood in that dropdown is checked in a lot of places. Working on this now.

**Comment by cspanring** [comment]
that is actually not such a high priority. if you could look at #94 please.

**Comment by tyrelsouza** [comment]
So if I add a blank option, the pagination doesn't work after that, it loads a new list,  but it will not update the map with the correct info marker icons and park geometries. Do you have any suggestions?
