### ISSUE TITLE
Plan A Trip functionality

### ISSUE THREAD

**Issue by marilynfletcher** [MAPC/bostonparks#63]
Use simple form layout for start and stop address.
Add "stops" to top navigation
"Remove" button should match other layouts
Add a "Reroute Trip" button to regenerate data when users reorders the stops.
Add graphic to indicate that stops are drag-able.

**Comment by tyrelsouza** [comment]
**Use simple form layout for start and stop address.**
**Add "stops" to top navigation**
**"Remove" button should match other layouts**
**Add a "Reroute Trip" button to regenerate data when users reorders the stops.**
Add graphic to indicate that stops are drag-able.

Finished bold parts.
