### ISSUE TITLE
Add Flag for objectionable content in park stories

### ISSUE THREAD

**Issue by hastclair** [MAPC/bostonparks#66]
Add Flag for objectionable content in park stories so users can flag rude etc comments in user stories. have email sent to us so we can we can review

**Comment by tyrelsouza** [comment]
We have the flag in place, and it will set the flag in the database, just waiting to find out who to email and what to email.

**Comment by tyrelsouza** [comment]
This is done, but needs a mail server running on the server. Sends the email to all emails in the ADMINS part of settings.
