### ISSUE TITLE
Explore: Show icons on map for selected park types.

### ISSUE THREAD

**Issue by marilynfletcher** [MAPC/bostonparks#69]

**Comment by cspanring** [comment]
currently there is no search for facilities on the explore page, so I have nothing to hook the map into. I just re-arranged some code on that page (5ecdf9994e7329ed171d1f37cc60ae3533e8c0ba), but wasn't sure how you planned the facility search.

**Comment by cspanring** [comment]
added #94 for the previous comment

**Comment by tyrelsouza** [comment]
Is there a hook in the javascript that allows me to  pass a list of parks, and then get the facilities mapped out on the list? I see loadparks, which maps the parks, but looking through, I don't see where the facilities are loaded.

**Comment by cspanring** [comment]
not very elegant, but there is a global map configuration that tell loadparks to go ahead and get the facilities too (https://github.com/MAPC/bostonparks/blob/develop/parkmap/static/parkmap/js/parkmap.js#L338). Add the following config directly in the script block in your template:

```
bp.mapconf = {
        "showfacilites": true
}
```

**Comment by cspanring** [comment]
this is done, but we have a new strange problem that I couldn't solve: #102
