### ISSUE TITLE
Flags on Park stories are too bold

### ISSUE THREAD

**Issue by hastclair** [MAPC/bostonparks#81]
The flags for bad content on Parks stories are too bold. I think they currently compete with the real content. Please make a mellow color like grey. It is possible the Marilyn has this on her radar screen but has not yet stylized the function. Just adding to issue list to be sure.

**Comment by marilynfletcher** [comment]
Holly --  I used the Bootstrap flag icon - if the black looks too strong, I can make a custom icon for the park page. --Marilyn

**Comment by hastclair** [comment]
Looks better! Thanks

On Fri, Jun 8, 2012 at 1:30 PM, Marilyn Fletcher <
reply@reply.github.com
