### ISSUE TITLE
Explore page: add typeahead to search field

### ISSUE THREAD

**Issue by marilynfletcher** [MAPC/bostonparks#86]

**Comment by tyrelsouza** [comment]
We should use this maybe? http://harvesthq.github.com/chosen/

**Comment by cspanring** [comment]
i used it in a few other projects, great library, but with Bootstrap 2 I found the built-in typeahead more consistent in terms of UI components. And it's pretty easy to use actually. http://twitter.github.com/bootstrap/javascript.html#typeahead

**Comment by tyrelsouza** [comment]
Wow that was definitely really easy to setup.
