### ISSUE TITLE
play: basketball + chinatown returns community garden in south dorcester as first result

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#89]
do the play results work?

**Comment by marilynfletcher** [comment]
Could this be the same data issue as issue #45?

**Comment by cspanring** [comment]
yep, the title looks very similar.

the map shows the correct facilities, it's just the list that's off.

**Comment by marilynfletcher** [comment]
Okay, these issues are resolved, it was a filter issue in resources.py
