### ISSUE TITLE
link activities and neighborhood dropdown menus

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#9]
only show activities that are available in neighborhoods and vice versa, whenever the two dropdowns appear together.

**Comment by tyrelsouza** [comment]
Does this mean on the homepage, show only two dropdowns  

Neighborhoods   in find a greenspace,

Activities   in Play

When either are selected, update the ui by adding another dropdown box to show the correlated  Neighborhood -> activities, or Activities -> Neighborhood?

**Comment by cspanring** [comment]
On the homepage there are neighborhood and activities in the play section (I just realized that #15 is a duplicate that I added, should be merged).

see for example the school district and school dropdown here: http://greenstreets.mapc.org/studentform/ only schools that are within the school district appear.

the basic idea is: we shouldn't list an activity that's not available in a neighborhood and shouldn't list neighborhoods that don't have the selected activity. those combination lead to an empty search results page and I think we can avoid this by catching non-existent combination before a user can select them.

**Comment by tyrelsouza** [comment]
If you check the latest changes I made to home.html, this should be happening. 

https://github.com/MAPC/bostonparks/commit/9f796ac194160f3f84a75ea34633a0a22b5cee2e

Is where I have this, it seems to have disappeared though. I will try to get this back and showing.

**Comment by tyrelsouza** [comment]
This has been pushed, please let me know if this behavior is the way you anticipate by pulling latest changes for parkmap/templates/parkmap/home.html

**Comment by cspanring** [comment]
Thanks, that's exactly what I meant.
