### ISSUE TITLE
Home: add full text search

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#90]
I think it would be good to have a text search field that searches in titles on homepage. opens explore page with search results.

**Comment by tyrelsouza** [comment]
In descriptions also? Does this mean the explore page on the current text search should search in descriptions as well? Or is that just in name?

**Comment by cspanring** [comment]
just the name

**Comment by cspanring** [comment]
This could just open the explore page with an URL parameter to perform the search and show the results. On Explore the search is already implemented.

**Comment by tyrelsouza** [comment]
christian: shall this just be the same as we have on the explore page?

**Comment by cspanring** [comment]
yes, I think it can use exactly the same search.

**Comment by cspanring** [comment]
Now that I'm trying it, because we use type ahead with park names, it would make more sense to land on the park page instead of the explore page.

What do you think?

**Comment by tyrelsouza** [comment]
The reason we do explore is because you could search for "soldier" and see both soldiers park and soldiers monument (not sure if real name) but we can switch to park page if that works.

**Comment by cspanring** [comment]
That makes sense too. Hold off on that please, I'll get some other (user) opinions.

**Comment by marilynfletcher** [comment]
Park page
