### ISSUE TITLE
Explore: shows parktypes instead of facilities

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#95]
should list all available facilitytypes

**Comment by marilynfletcher** [comment]
Christian, We've changed it to facility type - can you take a look? Is this correct? Should we add a scroll bar?

**Comment by cspanring** [comment]
Yes, there should be a scrollbar. The box can't be higher than the window. And the text search should still be visible.

-----Original Message-----

**Comment by tyrelsouza** [comment]
This is fixed. Now shows facilitytypes.
