### ISSUE TITLE
Slug on model class Facility is not unique

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#96]
Does it need to be unique?

**Comment by tyrelsouza** [comment]
I have made it unique now in the models.py file. It would make sense for it to be unique, as a slug is a lot easier on the eyes than someone seeing numbers all over the place and questioning what is being referred.

**Comment by tyrelsouza** [comment]
Although I'm not sure we even need a slug on Facility, I just checked and it isn't used ANYWHERE in the code. I will do some testing to see what commenting this out affects.

**Comment by cspanring** [comment]
That's what I thought. There is no facility page where a slug would be useful. We might as well drop it. Just wanted to confirm.

-----Original Message-----

**Comment by tyrelsouza** [comment]
Yeah, it's commented out.
