### ISSUE TITLE
Play: pagination doesn't work with map

### ISSUE THREAD

**Issue by cspanring** [MAPC/bostonparks#97]
all objects are shown on the first page, nothing is shown on map on sub pages.

**Comment by tyrelsouza** [comment]
This seems to  work now. Do you have an example of where it does not?

**Comment by tyrelsouza** [comment]
I have assigned this to you, so if it is done, feel free to close it, thanks.

**Comment by cspanring** [comment]
here it shows all facilities, on every page. related: #100

**Comment by cspanring** [comment]
closed by 5bca3ecb892f9f5d86df764b491babd69b16da51
